<div class="row">
    <div class="col-lg-12 pContent">
        <!-- 预览区 -->
        <div class="pPreview">
            <div id="previewArea" class="iphonePreview">
                <div class="previewArea">
                    <!-- Title -->
                    <div class="pageTitle">
                        <p id="title" name="title" class="imgShade" onclick="config(this, 'title')">欢迎使用由国创科视提供的免费Wi-Fi</p>
                    </div>

                    <!-- Banner -->
                    <div id="bannerCarousel" class="carousel slide">
                        <!-- 轮播（Carousel）项目 -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img id="banner" name="banner" src="/img/gcks/auth/banner/banner_01.jpg" class="img-responsive" onclick="config(this, 'banner');">
                            </div>
                        </div>
                    </div>

                    <!-- 副广告 -->
                    <div class="cityAvert">
                        <div class="cityAvertLeft">
                            <img id="cityAvert1" name="cityAvert1" src="/img/hot_app.png" class="img-responsive imgShade" onclick="config(this, 'cityAvert1');" alt="">
                        </div>
                        <div class="cityAvertRight">
                            <img id="cityAvert2" name="cityAvert2" src="/img/hot_game.png" class="img-responsive imgShade" onclick="config(this, 'cityAvert2');" alt="">
                        </div>
                    </div>

                    <!-- 热门应用/游戏 标题 -->
                    <div class="hotRecTitle">
                        <div class="hotRecTitleLeft">
                            <div class="hotRecTitleContent">
                                <div class="hotRecName">热门应用</div>
                                <div class="hotRecMore"><a href="#">更多</a></div>
                            </div>
                        </div>
                        <div class="hotRecTitleRight">
                            <div class="hotRecTitleContent">
                                <div class="hotRecName">热门游戏</div>
                                <div class="hotRecMore"><a href="#">更多</a></div>
                            </div>
                        </div>
                    </div>

                    <!-- 热门应用/游戏 图片 -->
                    <div class="hotRecImg">
                        <div class="hotRecImgLeft">
                            <img id="hotRec1" name="hotRec1" src="/img/hot_app.png" class="img-responsive imgShade" onclick="config(this, 'hotRec1');" alt="">
                        </div>
                        <div class="hotRecImgRight">
                            <img id="hotRec2" name="hotRec2" src="/img/hot_game.png" class="img-responsive imgShade" onclick="config(this, 'hotRec2');" alt="">
                        </div>
                    </div>

                    <!-- 热门视频 标题 -->
                    <div class="hotVedioTitle">
                        <div class="hotVedioName">
                            热门视频
                        </div>
                        <div class="hotVedioMore">
                            <a href="#">更多</a>
                        </div>
                    </div>

                    <!-- 热门视频 -->
                    <div class="hotVedio">
<!--                        <div class="no-left-right-padding mask-relative" onclick="">-->
<!--                            <div class="mask pt-click"></div>-->
<!--                            <div id="dop-content-container" class="dop-maxheight-100 dop-content-container "></div>-->
<!--                            <script src="http://10.32.8.157/appkweb/yXeYxfbrBPqJ/basic_insert_model/portal_banner/build/dop.init.insert3rd_61051,54674-basic_model_02.js" type="text/javascript"></script>-->
<!--                        </div>-->
                    </div>

                    <!-- 连接按钮 -->
                    <div class="connBtn">
                        <div class="connBtnLeft">
                            <button type="button" class="btn btn-success connBtnWechat">
                                <i class="fa fa-wechat fa-lg" aria-hidden="true"></i>
                                <span>微信连WiFi</span>
                            </button>
                        </div>

                        <div class="connBtnRight">
                            <button type="button" class="btn btn-info connBtnPhone">
                                <i class="fa fa-mobile fa-lg pic" aria-hidden="true"></i>
                                <span>手机号连WiFi</span>
                            </button>
                        </div>
                    </div>

                    <!-- 版权信息 -->
                    <div>
                        <img id="copyright" name="copyright" src="/img/copyright.png" class="img-responsive imgShade" onclick="config(this, 'copyright');" alt="">
                    </div>
                </div>
            </div>
        </div>

        <!--编辑区-->
        <div id="editArea" class="pEdit">
            <form id="addForm">
                <input id="resType" name="resType" type="hidden" value="20002">

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <h3 id="configTitle" style="text-align: center;">Banner配置</h3>
                        </div>
                    </div>

                    <!-- 资源名称 -->
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="resName"><i class="fa fa-flag"></i> 资源名称<span class="help-msg">(必填,最长20个汉字)</span></label>
                                <input type="text" class="form-control" id="resName" name="resName" placeholder="请输入具有唯一标识的资源名称"
                                    required maxlength="20">
                            </div>
                        </div>
                    </div>

                    <!-- 选择城市 -->
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label><i class="fa fa-map"></i> 选择城市<span class="help-msg">(可选)</span></label>
                                <select name="cityId" class="form-control select2" style="width: 100%;">
                                    <option value="0" selected="selected">选择城市</option>
                                    {% for city in cityList %}
                                        <option value="{{ city.me_id }}">{{ city.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>

                    <!-- 页眉标题 -->
                    <div class="row hide" id="pageTitle">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="titleContent"><i class="fa fa-header"></i> 页眉标题内容<span class="help-msg">(必填,最长25个汉字)</span></label>
                                <input type="text" class="form-control" id="titleContent" name="titleContent" placeholder="请输入页眉标题内容" minlength="2" maxlength="25">
                            </div>
                        </div>
                    </div>

                    <!-- 图片上传 -->
                    <div class="row" id="resImage">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="resImg"><i class="fa fa-image"></i> 资源图片<span class="help-msg">(必填,要求高度:px, 宽度:px)</span></label>
                                    <input id="resImg" name="resImg" type="file" accept="image/jpeg,image/png,image/jpg,image/gif">
<!--                                <input id="logo" type="file" accept="image/jpeg,image/png,image/jpg,image/gif" onchange="imgPreview(this, 'imgPreviewDiv')">-->
<!--                                <div id="imgPreviewDiv" style="max-width: 200px; max-height: 200px;"></div>-->
                            </div>
                        </div>
                    </div>

                    <!-- 图片点击链接URL -->
                    <div class="row hide" id="imgHrefUrl">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="resImgHref"><i class="fa fa-link"></i> 资源图片点击链接<span class="help-msg">(必填)</span></label>
                                <input type="url" class="form-control" id="resImgHref" name="resImgHref" placeholder="请输入资源图片点击链接">
                            </div>
                        </div>
                    </div>

                    <!-- 应用/游戏Android下载链接URL -->
                    <div class="row hide" id="androidUrl">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="androidHref"><i class="fa fa-android"></i> Android下载链接URL<span class="help-msg">(必填)</span></label>
                                <input type="url" class="form-control" id="androidHref" name="androidHref" placeholder="请输入Android下载链接URL">
                            </div>
                        </div>
                    </div>

                    <!-- 应用/游戏iOS下载链接URL -->
                    <div class="row hide" id="iosUrl">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="iosHref"><i class="fa fa-apple"></i> iOS下载链接URL<span class="help-msg">(必填)</span></label>
                                <input type="url" class="form-control" id="iosHref" name="iosHref" placeholder="请输入iOS下载链接URL">
                            </div>
                        </div>
                    </div>

                    <!-- 保存/重置按钮 -->
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <button id="saveButton" type="button" class="btn btn-primary" style="width: 200px;">保存</button>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <button type="reset" class="btn btn-danger" style="width: 200px;">重置</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Select2 -->
<script src="/adminlte/plugins/select2/select2.full.min.js"></script>

<!-- iCheck 1.0.1 -->
<script src="/adminlte/plugins/iCheck/icheck.min.js"></script>

<!-- 图片预览 -->
<script src="/js/imgPreview.js"></script>

<script>

    $('#bannerCarousel').carousel({
        interval: 2000
    });

    $(".select2").select2();

    /**
     * 配置
     * @param obj
     */
    function config(obj, type) {
        if($("#title").hasClass("imgShade") == false) {
            $("#title").addClass("imgShade");
        }

        if($("#banner").hasClass("imgShade") == false) {
            $("#banner").addClass("imgShade");
        }

        if($("#cityAvert1").hasClass("imgShade") == false) {
            $("#cityAvert1").addClass("imgShade");
        }

        if($("#cityAvert2").hasClass("imgShade") == false) {
            $("#cityAvert2").addClass("imgShade");
        }

        if($("#hotRec1").hasClass("imgShade") == false) {
            $("#hotRec1").addClass("imgShade");
        }

        if($("#hotRec2").hasClass("imgShade") == false) {
            $("#hotRec2").addClass("imgShade");
        }

        if($("#copyright").hasClass("imgShade") == false) {
            $("#copyright").addClass("imgShade");
        }

        var objId = obj.id;
        if($(obj).hasClass('imgShade') == true){
            $(obj).removeClass('imgShade');
        }

        switch (type){
            case "title":
                $("#configTitle").html("页眉标题配置");
                $("#resType").val(20001);

                configTitle();

                break;
            case "banner":
                $("#configTitle").html("Banner配置");
                $("#resType").val(20002);

                configBanner();
                break;
            case "cityAvert1":
                $("#configTitle").html("地市广告配置");
                $("#resType").val(20003);

                configCityAvert();
                break;
            case "cityAvert2":
                $("#configTitle").html("地市配置");
                $("#resType").val(20003);

                configCityAvert();
                break;
            case "hotRec1":
                $("#configTitle").html("热门推荐配置");
                $("#resType").val(20004);

                confgHotRec();
                break;
            case "hotRec2":
                $("#configTitle").html("热门推荐配置");
                $("#resType").val(20004);

                confgHotRec();
                break;
            case "copyright":
                $("#configTitle").html("版权信息配置");
                $("#resType").val(20005);

                configCopyright();
                break;
            default:

        }
    }

    /**
     * 页眉标题配置
     */
    function configTitle(){
        if($("#androidUrl").hasClass('hide') == false){
            $("#androidUrl").addClass('hide');
        }

        if($("#iosUrl").hasClass('hide') == false){
            $("#iosUrl").addClass('hide');
        }

        if($("#imgHrefUrl").hasClass('hide') == false){
            $("#imgHrefUrl").addClass('hide');
        }

        if($("#pageTitle").hasClass('hide') == true){
            $("#pageTitle").removeClass('hide');
        }


        if($("#resImage").hasClass('hide') == false){
            $("#resImage").addClass('hide');
        }
    }

    /**
     * Banner配置
     */
    function configBanner() {
        if($("#androidUrl").hasClass('hide') == false){
            $("#androidUrl").addClass('hide');
        }

        if($("#iosUrl").hasClass('hide') == false){
            $("#iosUrl").addClass('hide');
        }

        if($("#imgHrefUrl").hasClass('hide') == false){
            $("#imgHrefUrl").addClass('hide');
        }

        if($("#pageTitle").hasClass('hide') == false){
            $("#pageTitle").addClass('hide');
        }

        if($("#resImage").hasClass('hide') == true){
            $("#resImage").removeClass('hide');
        }

    }

    function configCityAvert() {
        if($("#androidUrl").hasClass('hide') == false){
            $("#androidUrl").addClass('hide');
        }

        if($("#resImage").hasClass('hide') == true){
            $("#resImage").removeClass('hide');
        }

        if($("#iosUrl").hasClass('hide') == false){
            $("#iosUrl").addClass('hide');
        }

        if($("#imgHrefUrl").hasClass('hide') == true){
            $("#imgHrefUrl").removeClass('hide');
        }

        if($("#pageTitle").hasClass('hide') == false){
            $("#pageTitle").addClass('hide');
        }

    }

    /**
     * 热门推荐
     */
    function confgHotRec() {
        if($("#androidUrl").hasClass('hide') == true){
            $("#androidUrl").removeClass('hide');
        }

        if($("#iosUrl").hasClass('hide') == true){
            $("#iosUrl").removeClass('hide');
        }

        if($("#imgHrefUrl").hasClass('hide') == false){
            $("#imgHrefUrl").addClass('hide');
        }

        if($("#pageTitle").hasClass('hide') == false){
            $("#pageTitle").addClass('hide');
        }

        if($("#resImage").hasClass('hide') == true){
            $("#resImage").removeClass('hide');
        }

    }

    /**
     * 版权信息
     */
    function configCopyright() {
        if($("#androidUrl").hasClass('hide') == false){
            $("#androidUrl").addClass('hide');
        }

        if($("#iosUrl").hasClass('hide') == false){
            $("#iosUrl").addClass('hide');
        }

        if($("#imgHrefUrl").hasClass('hide') == true){
            $("#imgHrefUrl").removeClass('hide');
        }

        if($("#pageTitle").hasClass('hide') == false){
            $("#pageTitle").addClass('hide');
        }

        if($("#resImage").hasClass('hide') == true){
            $("#resImage").removeClass('hide');
        }
    }

    //保存
    $("#saveButton").click(function () {
        $("#saveButton").attr('disabled', 'disabled');

        var resType = $("#resType").val();

        $.ajax({
            cache: false,
            type: "POST",
            url: "/rauth1/save",
            data:$('#addForm').serialize(),
            dataType: "json",
            async: false,
            error: function() {
                alert("保存失败，请稍后再试！");

                $("#saveButton").removeAttr('disabled');
            },
            success: function(response) {
                if(response.code == 0){
                    alert("保存成功！");
                    $('#addForm')[0].reset();
                }else{
                    alert("错误：" + response.message);
                }

                $("#saveButton").removeAttr('disabled');
            }
        });

    });

</script>
